### ISSUE TITLE
file ooopy/ooopy/Transformer.py

### ISSUE THREAD

**Issue by WeeSee** [gebi/ooopy#6]
I do not have python experience but in file 

`ooopy/ooopy/Transformer.py `

in class `Transformer` there are lots of  sample data as:

        firstname : Erika
        lastname : Nobody
        firstname : Eric
        lastname : Wizard
        firstname : Hugo
        lastname : Testman
        firstname : Erika

Why? This should be eliminated in a tool for general use.

**Comment by gebi** [comment]
yes it looks strange, but i don't want to remove something that does not harm anyone and might server as documentation as a deviation from upstream.

**Comment by gebi** [comment]
Ah... the original author used doctests, which means basically all unit tests are embedded in doc strings, thats why there is so much sample data and code embedded inside the doc strings...

running the tests someone has to wonder why anything in this projects works at all...
